name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Build
      run: go build
    
    - name: Gotest
      run: go test ./... -coverprofile=c.out
    
    - name: Install Gocov
      run: go get github.com/axw/gocov/gocov
    
    - name: Generate Report
      run: gocov convert ./c.out | gocov report > coverage.json

    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: ad66eb9762f8b7fe194ead2bc63e93d1ed1d87d680feb0b114aa19bd2c7090bf
      with:
        coverageCommand: go test ./... -coverprofile=c.out
        debug: true
    

    
