name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Gotest
      run: go test ./... -coverprofile=c.out
    
    - name: Install Gocov
      run: go get github.com/axw/gocov/gocov
    
    - name: Generate Report
      run: gocov convert ./c.out | gocov report > coverage.json

    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: e5e29749a794f106041f0506f9fe3e111f509769687802eaf94e46d075ad44f9
      with:
        coverageCommand: ls
        debug: true
    

    
