name: Go

on:
  push:
    branches: [ all ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
  
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
    
    - name: Build
      run: go build

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: mirromutth/mysql-action@v1.1
      with:
        host port: 3306 # Optional, default value is 3306. The port of host
        container port: 3306 # Optional, default value is 3306. The port of container
        character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
        collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
        mysql version: '8.0' # Optional, default value is "latest". The version of the MySQL
        mysql database: 'PlayerScoreDB' # Optional, default value is "test". The specified database which will be create
        mysql root password: 1234 #${{ secrets.RootPassword }} # Required if "mysql user" is empty, default is empty. The root superuser password
        

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Gotest
      run: |
        go test ./... -coverprofile=c.out
        sed -i "s|github.com/hyun06000/go-backend-with-cleancode-and-tdd|.|g" c.out
    
    - name: Install Gocov
      run: |
        go get github.com/axw/gocov/gocov
        gocov test ./... | gocov report
        
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: e5e29749a794f106041f0506f9fe3e111f509769687802eaf94e46d075ad44f9
      
